### ISSUE TITLE
Node 4 support

### ISSUE THREAD

**Issue by haltcase** [lightscript/babel-plugin-lightscript#10]
While [Node 4 is still maintained](https://github.com/nodejs/LTS#lts-schedule) it might be smart to have this plugin support it. This is especially true since it makes it difficult for third parties using LightScript to maintain node 4 support. Once April 1st 2018 rolls around it can be dropped for good.

For example, my shiny new [babel plugin](https://github.com/citycide/babel-plugin-partial-application) fails to build in my node 4 test environment because this plugin can't be parsed, even though I'm targeting node >= 4.

Should be easy enough to swap out `babel-preset-eslatest-node6` for `babel-preset-env` and set the target, and that's easily updated in a year when node 4 dies. Thoughts?

**Comment by rattrayalex** [comment]
Yeah, sounds like a good call. Would welcome a PR, or I can take it on within a few days. 

Would also probably be a good idea to set up Travis to automate testing on Node 4...

**Comment by rattrayalex** [comment]
heck, no reason not to support archaic versions of Node too...

**Comment by haltcase** [comment]
> heck, no reason not to support archaic versions of Node too...

You mean 0.x? I wouldn't. They're actively _not_ maintained :)
