### ISSUE TITLE
gulp

### ISSUE THREAD

**Issue by yukulele** [lightscript/babel-plugin-lightscript#20]
Is it posible to compile lightscript via gulp? is there a `gulp-lightscript` library?

**Comment by haltcase** [comment]
You should just use [gulp-babel](https://github.com/babel/gulp-babel) and the lightscript preset or plugin:

```js
const gulp = require('gulp')
const babel = require('gulp-babel')

gulp.task('default', () =>
  gulp.src('src/app.js')
    .pipe(babel({
      presets: ['lightscript']
      // or for just the language:
      // plugins: ['lightscript']
    }))
    .pipe(gulp.dest('dist'))
)
```

**Comment by rattrayalex** [comment]
@citycide is correct (thanks for sharing an example!) – hope this is ok to close @yukulele ?

**Comment by rattrayalex** [comment]
By the way, we're happy to help with little things as you get started in the gitter chat if you have more questions – http://gitter.im/lightscript/Lobby – though you're certainly more than welcome to open issues as well! (this one was certainly appropriate)

**Comment by yukulele** [comment]
Thanks, perfect !
