### ISSUE TITLE
Stdlib internal methods -- inline them?

### ISSUE THREAD

**Issue by wcjohnson** [lightscript/babel-plugin-lightscript#8]
If you use one of the non-lodash stdlib methods like `looseEq` the AST transforms automatically import `babel-plugin-lightscript` into the final code.

Since babel plugins are `devDependencies` 100% of the time in the current ecosystem, I don't think most people will realize that they need `babel-plugin-lightscript` as a `dependency` rather than a `devDependency` which means their app may crash when `NODE_ENV="production"`. And I'm not sure making a Babel plugin into a `dependency` is a good idea even if it is well documented that you need it.

Would you consider just inlining the builtin stdlib methods using AST transforms since they are all oneliners anyway?

**Comment by rattrayalex** [comment]
I should have thought of that - good call. Yeah inlining sounds like the way to go

**Comment by rattrayalex** [comment]
@wcjohnson do you want to implement this or shall I?

**Comment by wcjohnson** [comment]
@rattrayalex 

May have to give this one a miss, I need to spend some time on the paying gig, they'll be wondering where I've been all week. :)

**Comment by rattrayalex** [comment]
😄 sounds good!

**Comment by rattrayalex** [comment]
Addressed in #16
